---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: adsb
    app.kubernetes.io/name: controller
  name: adsbs.illallangi.enterprises
spec:
  group: illallangi.enterprises
  names:
    kind: ADSB
    listKind: ADSBList
    plural: adsbs
    singular: adsb
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.adsb.webDomain
      name: Domain
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              adsb:
                properties:
                  backup:
                    properties:
                      b2AccountId:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2AccountKey:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2repo:
                        type: string
                      resticPassword:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      schedule:
                        default: 0 30 3 * * *
                        type: string
                    required:
                    - resticPassword
                    - b2AccountId
                    - b2AccountKey
                    - b2repo
                    type: object
                  fence:
                    properties:
                      distance:
                        type: number
                      mastodon:
                        properties:
                          accessToken:
                            oneOf:
                            - required:
                              - secretKeyRef
                            properties:
                              secretKeyRef:
                                properties:
                                  key:
                                    type: string
                                  name:
                                    type: string
                                required:
                                - key
                                - name
                                type: object
                            type: object
                          server:
                            type: string
                        required:
                        - accessToken
                        - server
                        type: object
                    required:
                    - distance
                    - mastodon
                    type: object
                  fr24feed:
                    properties:
                      sharingKey:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                    required:
                    - sharingKey
                    type: object
                  planeWatch:
                    properties:
                      apiKey:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                    required:
                    - apiKey
                    type: object
                  position:
                    properties:
                      altitude:
                        type: number
                      latitude:
                        type: number
                      longitude:
                        type: number
                    required:
                    - altitude
                    - latitude
                    - longitude
                    type: object
                  storage:
                    properties:
                      resources:
                        default:
                          requests:
                            storage: 16Gi
                        properties:
                          requests:
                            default:
                              storage: 16Gi
                            properties:
                              storage:
                                default: 16Gi
                                type: string
                            type: object
                        type: object
                      storageClassName:
                        type: string
                    required:
                    - storageClassName
                    type: object
                  title:
                    default: ADSB
                    type: string
                  webDomain:
                    type: string
                required:
                - position
                - storage
                - webDomain
                type: object
              cloudflare:
                properties:
                  apiToken:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                required:
                - apiToken
                type: object
            required:
            - cloudflare
            - adsb
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: adsb
    app.kubernetes.io/name: controller
  name: adsb-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: adsb
    app.kubernetes.io/name: controller
  name: adsb-controller
rules:
- apiGroups:
  - illallangi.enterprises
  resources:
  - adsbs
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: adsb
    app.kubernetes.io/name: controller
  name: adsb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: adsb-controller
subjects:
- kind: ServiceAccount
  name: adsb-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: adsb
    app.kubernetes.io/name: controller
  name: adsb-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: adsb
      app.kubernetes.io/name: controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: adsb-controller
      labels:
        app.kubernetes.io/instance: adsb
        app.kubernetes.io/name: controller
    spec:
      containers:
      - image: ghcr.io/illallangi/adsb-controller:latest
        imagePullPolicy: Always
        name: adsb-controller
      serviceAccount: adsb-controller
      serviceAccountName: adsb-controller
