---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: hook-operator
  name: adsbs.illallangi.enterprises
spec:
  group: illallangi.enterprises
  names:
    kind: ADSB
    listKind: ADSBList
    plural: adsbs
    singular: adsb
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              cloudflare:
                properties:
                  apiToken:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                required:
                - apiToken
                type: object
              fence:
                properties:
                  distance:
                    type: number
                  mastodon:
                    properties:
                      accessToken:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      server:
                        type: string
                    required:
                    - accessToken
                    - server
                    type: object
                required:
                - distance
                - mastodon
                type: object
              fr24feed:
                properties:
                  sharingKey:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                required:
                - sharingKey
                type: object
              position:
                properties:
                  altitude:
                    type: number
                  latitude:
                    type: number
                  longitude:
                    type: number
                required:
                - altitude
                - latitude
                - longitude
                type: object
              title:
                default: ADSB
                type: string
              url:
                type: string
            required:
            - cloudflare
            - position
            - url
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: hook-operator
  name: adsbs.illallangi.enterprises
spec:
  group: illallangi.enterprises
  names:
    kind: ADSB
    listKind: ADSBList
    plural: adsbs
    singular: adsb
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              cloudflare:
                properties:
                  apiToken:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                required:
                - apiToken
                type: object
              fence:
                properties:
                  distance:
                    type: number
                  mastodon:
                    properties:
                      accessToken:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      server:
                        type: string
                    required:
                    - accessToken
                    - server
                    type: object
                required:
                - distance
                - mastodon
                type: object
              fr24feed:
                properties:
                  sharingKey:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                required:
                - sharingKey
                type: object
              position:
                properties:
                  altitude:
                    type: number
                  latitude:
                    type: number
                  longitude:
                    type: number
                required:
                - altitude
                - latitude
                - longitude
                type: object
              title:
                default: ADSB
                type: string
              url:
                type: string
            required:
            - cloudflare
            - position
            - url
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: adsb-controller
  name: adsb-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: adsb-controller
  name: adsb-controller
rules:
- apiGroups:
  - illallangi.enterprises
  resources:
  - adsbs
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: adsb-controller
  name: adsb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: adsb-controller
subjects:
- kind: ServiceAccount
  name: adsb-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: adsb-controller
  name: adsb-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: adsb-controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: adsb-controller
      labels:
        app.kubernetes.io/name: adsb-controller
    spec:
      containers:
      - image: ghcr.io/illallangi/adsb-controller:latest
        imagePullPolicy: Always
        name: adsb-controller
      serviceAccount: adsb-controller
      serviceAccountName: adsb-controller
