---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: ais-operator
  name: aiss.illallangi.enterprises
spec:
  group: illallangi.enterprises
  names:
    kind: AIS
    listKind: AISList
    plural: aiss
    singular: ais
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              cloudflare:
                properties:
                  apiToken:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                required:
                - apiToken
                type: object
              position:
                properties:
                  altitude:
                    type: number
                  latitude:
                    type: number
                  longitude:
                    type: number
                required:
                - altitude
                - latitude
                - longitude
                type: object
              title:
                default: AIS
                type: string
            required:
            - cloudflare
            - position
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: ais-controller
  name: ais-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ais-controller
  name: ais-controller
rules:
- apiGroups:
  - illallangi.enterprises
  resources:
  - aiss
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ais-controller
  name: ais-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ais-controller
subjects:
- kind: ServiceAccount
  name: ais-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ais-controller
  name: ais-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ais-controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: ais-controller
      labels:
        app.kubernetes.io/name: ais-controller
    spec:
      containers:
      - image: ghcr.io/illallangi/ais-controller:latest
        imagePullPolicy: Always
        name: ais-controller
      serviceAccount: ais-controller
      serviceAccountName: ais-controller
