---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: ais
    app.kubernetes.io/name: controller
  name: aiss.illallangi.enterprises
spec:
  group: illallangi.enterprises
  names:
    kind: AIS
    listKind: AISList
    plural: aiss
    singular: ais
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.ais.webDomain
      name: Domain
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              ais:
                properties:
                  backup:
                    properties:
                      b2AccountId:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2AccountKey:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2repo:
                        type: string
                      resticPassword:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      schedule:
                        default: 0 30 3 * * *
                        type: string
                    required:
                    - resticPassword
                    - b2AccountId
                    - b2AccountKey
                    - b2repo
                    type: object
                  position:
                    properties:
                      latitude:
                        type: number
                      longitude:
                        type: number
                    required:
                    - latitude
                    - longitude
                    type: object
                  shipXplorer:
                    properties:
                      serialNumber:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      sharingKey:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                    required:
                    - serialNumber
                    - sharingKey
                    type: object
                  storage:
                    properties:
                      resources:
                        default:
                          requests:
                            storage: 16Gi
                        properties:
                          requests:
                            default:
                              storage: 16Gi
                            properties:
                              storage:
                                default: 16Gi
                                type: string
                            type: object
                        type: object
                      storageClassName:
                        type: string
                    required:
                    - storageClassName
                    type: object
                  title:
                    default: AIS
                    type: string
                  udpFeeds:
                    default: []
                    items:
                      properties:
                        host:
                          type: string
                        port:
                          default: 6555
                          type: integer
                      required:
                      - host
                      type: object
                    type: array
                  webDomain:
                    type: string
                required:
                - position
                - shipXplorer
                - storage
                - webDomain
                type: object
            required:
            - ais
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ais
    app.kubernetes.io/name: controller
  name: ais-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: ais
    app.kubernetes.io/name: controller
  name: ais-controller
rules:
- apiGroups:
  - illallangi.enterprises
  resources:
  - aiss
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ais
    app.kubernetes.io/name: controller
  name: ais-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ais-controller
subjects:
- kind: ServiceAccount
  name: ais-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ais
    app.kubernetes.io/name: controller
  name: ais-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ais
      app.kubernetes.io/name: controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: ais-controller
      labels:
        app.kubernetes.io/instance: ais
        app.kubernetes.io/name: controller
    spec:
      containers:
      - image: ghcr.io/illallangi/ais-controller:latest
        imagePullPolicy: Always
        name: ais-controller
      serviceAccount: ais-controller
      serviceAccountName: ais-controller
