---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: data-operator
  name: datas.illallangi.enterprises
spec:
  group: illallangi.enterprises
  names:
    kind: Data
    listKind: DataList
    plural: datas
    singular: data
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.data.webDomain
      name: Domain
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              data:
                properties:
                  backup:
                    properties:
                      b2AccountId:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2AccountKey:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2repo:
                        type: string
                      exclude:
                        default:
                        - src/deluge/**
                        - obj/**
                        - pub/**
                        items:
                          type: string
                        type: array
                      resticPassword:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      schedule:
                        default: 0 30 3 * * *
                        type: string
                    required:
                    - resticPassword
                    - b2AccountId
                    - b2AccountKey
                    - b2repo
                    type: object
                  storage:
                    properties:
                      resources:
                        default:
                          requests:
                            storage: 32Ti
                        properties:
                          requests:
                            default:
                              storage: 32Ti
                            properties:
                              storage:
                                default: 32Ti
                                type: string
                            type: object
                        type: object
                      storageClassName:
                        type: string
                    required:
                    - storageClassName
                    type: object
                  webDomain:
                    pattern: ^[a-z][a-z0-9-]*\.great-tuna\.ts\.net$
                    type: string
                required:
                - storage
                - webDomain
                type: object
            required:
            - data
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: data-controller
  name: data-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: data-controller
  name: data-controller
rules:
- apiGroups:
  - illallangi.enterprises
  resources:
  - datas
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: data-controller
  name: data-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: data-controller
subjects:
- kind: ServiceAccount
  name: data-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: data-controller
  name: data-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: data-controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: data-controller
      labels:
        app.kubernetes.io/name: data-controller
    spec:
      containers:
      - image: ghcr.io/illallangi/data-controller:latest
        imagePullPolicy: Always
        name: data-controller
      serviceAccount: data-controller
      serviceAccountName: data-controller
