---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: gatus
    app.kubernetes.io/name: controller
  name: gatuses.illallangi.enterprises
spec:
  group: illallangi.enterprises
  names:
    kind: Gatus
    listKind: GatusList
    plural: gatuses
    singular: gatus
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.gatus.webDomain
      name: Domain
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              cloudflare:
                properties:
                  apiToken:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                required:
                - apiToken
                type: object
              gatus:
                properties:
                  groups:
                    items:
                      properties:
                        endpoints:
                          items:
                            properties:
                              name:
                                type: string
                              url:
                                type: string
                            required:
                            - name
                            - url
                            type: object
                          minItems: 1
                          type: array
                        name:
                          type: string
                      required:
                      - endpoints
                      - name
                      type: object
                    minItems: 1
                    type: array
                  webDomain:
                    type: string
                required:
                - groups
                - webDomain
                type: object
              postgresql:
                properties:
                  backup:
                    properties:
                      b2AccountId:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2AccountKey:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2repo:
                        type: string
                      resticPassword:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      schedule:
                        default: 0 30 3 * * *
                        type: string
                    required:
                    - resticPassword
                    - b2AccountId
                    - b2AccountKey
                    - b2repo
                    type: object
                  password:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                  storage:
                    properties:
                      resources:
                        default:
                          requests:
                            storage: 16Gi
                        properties:
                          requests:
                            default:
                              storage: 16Gi
                            properties:
                              storage:
                                default: 16Gi
                                type: string
                            type: object
                        type: object
                      storageClassName:
                        type: string
                    required:
                    - storageClassName
                    type: object
                required:
                - password
                - storage
                type: object
            required:
            - cloudflare
            - gatus
            - postgresql
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: gatus
    app.kubernetes.io/name: controller
  name: gatus-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: gatus
    app.kubernetes.io/name: controller
  name: gatus-controller
rules:
- apiGroups:
  - illallangi.enterprises
  resources:
  - gatuses
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: gatus
    app.kubernetes.io/name: controller
  name: gatus-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gatus-controller
subjects:
- kind: ServiceAccount
  name: gatus-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: gatus
    app.kubernetes.io/name: controller
  name: gatus-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: gatus
      app.kubernetes.io/name: controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: gatus-controller
      labels:
        app.kubernetes.io/instance: gatus
        app.kubernetes.io/name: controller
    spec:
      containers:
      - image: ghcr.io/illallangi/gatus-controller:latest
        imagePullPolicy: Always
        name: gatus-controller
      serviceAccount: gatus-controller
      serviceAccountName: gatus-controller
