---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: generic
    app.kubernetes.io/name: controller
  name: generics.illallangi.enterprises
spec:
  group: illallangi.enterprises
  names:
    kind: Generic
    listKind: GenericList
    plural: generics
    singular: generic
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.generic.webDomain
      name: Domain
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              generic:
                properties:
                  data:
                    items:
                      properties:
                        name:
                          type: string
                        path:
                          type: string
                        subPath:
                          type: string
                      required:
                      - name
                      - path
                      type: object
                    type: array
                  image:
                    type: string
                  port:
                    default: 80
                    type: integer
                  probePath:
                    type: string
                  webDomain:
                    type: string
                required:
                - image
                - webDomain
                type: object
            required:
            - generic
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: generic
    app.kubernetes.io/name: controller
  name: generic-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: generic
    app.kubernetes.io/name: controller
  name: generic-controller
rules:
- apiGroups:
  - illallangi.enterprises
  resources:
  - generics
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: generic
    app.kubernetes.io/name: controller
  name: generic-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: generic-controller
subjects:
- kind: ServiceAccount
  name: generic-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: generic
    app.kubernetes.io/name: controller
  name: generic-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: generic
      app.kubernetes.io/name: controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: generic-controller
      labels:
        app.kubernetes.io/instance: generic
        app.kubernetes.io/name: controller
    spec:
      containers:
      - image: ghcr.io/illallangi/generic-controller:latest
        imagePullPolicy: Always
        name: generic-controller
      serviceAccount: generic-controller
      serviceAccountName: generic-controller
