---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/name: controller
  name: mastodons.illallangi.enterprises
spec:
  group: illallangi.enterprises
  names:
    kind: Mastodon
    listKind: MastodonList
    plural: mastodons
    singular: mastodon
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.mastodon.webDomain
      name: Domain
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              gid:
                default: 1000
                type: integer
              mastodon:
                properties:
                  backup:
                    properties:
                      b2AccountId:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2AccountKey:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2repo:
                        type: string
                      resticPassword:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      schedule:
                        default: 0 30 3 * * *
                        type: string
                    required:
                    - resticPassword
                    - b2AccountId
                    - b2AccountKey
                    - b2repo
                    type: object
                  localDomain:
                    type: string
                  otpSecret:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                  secretKeyBase:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                  storage:
                    properties:
                      resources:
                        default:
                          requests:
                            storage: 16Gi
                        properties:
                          requests:
                            default:
                              storage: 16Gi
                            properties:
                              storage:
                                default: 16Gi
                                type: string
                            type: object
                        type: object
                      storageClassName:
                        type: string
                    required:
                    - storageClassName
                    type: object
                  vapidPrivateKey:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                  vapidPublicKey:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                  webDomain:
                    type: string
                required:
                - localDomain
                - webDomain
                - otpSecret
                - secretKeyBase
                - vapidPrivateKey
                - vapidPublicKey
                - storage
                type: object
              postgresql:
                properties:
                  backup:
                    properties:
                      b2AccountId:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2AccountKey:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2repo:
                        type: string
                      resticPassword:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      schedule:
                        default: 0 30 3 * * *
                        type: string
                    required:
                    - resticPassword
                    - b2AccountId
                    - b2AccountKey
                    - b2repo
                    type: object
                  password:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                  storage:
                    properties:
                      resources:
                        default:
                          requests:
                            storage: 16Gi
                        properties:
                          requests:
                            default:
                              storage: 16Gi
                            properties:
                              storage:
                                default: 16Gi
                                type: string
                            type: object
                        type: object
                      storageClassName:
                        type: string
                    required:
                    - storageClassName
                    type: object
                required:
                - password
                - storage
                type: object
              redis:
                properties:
                  backup:
                    properties:
                      b2AccountId:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2AccountKey:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2repo:
                        type: string
                      resticPassword:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      schedule:
                        default: 0 30 3 * * *
                        type: string
                    required:
                    - resticPassword
                    - b2AccountId
                    - b2AccountKey
                    - b2repo
                    type: object
                  storage:
                    properties:
                      resources:
                        default:
                          requests:
                            storage: 16Gi
                        properties:
                          requests:
                            default:
                              storage: 16Gi
                            properties:
                              storage:
                                default: 16Gi
                                type: string
                            type: object
                        type: object
                      storageClassName:
                        type: string
                    required:
                    - storageClassName
                    type: object
                required:
                - storage
                type: object
              smtp:
                properties:
                  from:
                    type: string
                  host:
                    type: string
                  password:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                  port:
                    default: 587
                    type: integer
                  username:
                    type: string
                required:
                - from
                - host
                - password
                - username
                type: object
              uid:
                default: 1000
                type: integer
            required:
            - mastodon
            - postgresql
            - redis
            - smtp
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/name: controller
  name: mastodon-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/name: controller
  name: mastodon-controller
rules:
- apiGroups:
  - illallangi.enterprises
  resources:
  - mastodons
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/name: controller
  name: mastodon-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mastodon-controller
subjects:
- kind: ServiceAccount
  name: mastodon-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/name: controller
  name: mastodon-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mastodon
      app.kubernetes.io/name: controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: mastodon-controller
      labels:
        app.kubernetes.io/instance: mastodon
        app.kubernetes.io/name: controller
    spec:
      containers:
      - image: ghcr.io/illallangi/mastodon-controller:latest
        imagePullPolicy: Always
        name: mastodon-controller
      serviceAccount: mastodon-controller
      serviceAccountName: mastodon-controller
