---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: pigallery2-operator
  name: pigallerys.illallangi.enterprises
spec:
  group: illallangi.enterprises
  names:
    kind: PiGallery
    listKind: PiGalleryList
    plural: pigallerys
    singular: pigallery
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              cloudflare:
                properties:
                  apiToken:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                required:
                - apiToken
                type: object
              pigallery:
                properties:
                  title:
                    type: string
                  webDomain:
                    type: string
                required:
                - webDomain
                type: object
            required:
            - cloudflare
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: pigallery-controller
  name: pigallery-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pigallery-controller
  name: pigallery-controller
rules:
- apiGroups:
  - illallangi.enterprises
  resources:
  - pigallerys
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: pigallery-controller
  name: pigallery-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pigallery-controller
subjects:
- kind: ServiceAccount
  name: pigallery-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: pigallery-controller
  name: pigallery-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pigallery-controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: pigallery-controller
      labels:
        app.kubernetes.io/name: pigallery-controller
    spec:
      containers:
      - image: ghcr.io/illallangi/pigallery-controller:latest
        imagePullPolicy: Always
        name: pigallery-controller
      serviceAccount: pigallery-controller
      serviceAccountName: pigallery-controller
