---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: controller
  name: plexes.illallangi.enterprises
spec:
  group: illallangi.enterprises
  names:
    kind: Plex
    listKind: PlexList
    plural: plexes
    singular: plex
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.plex.webDomain
      name: Domain
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              plex:
                properties:
                  backup:
                    properties:
                      b2AccountId:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2AccountKey:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      b2repo:
                        type: string
                      resticPassword:
                        oneOf:
                        - required:
                          - secretKeyRef
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      schedule:
                        default: 0 30 3 * * *
                        type: string
                    required:
                    - resticPassword
                    - b2AccountId
                    - b2AccountKey
                    - b2repo
                    type: object
                  data:
                    items:
                      properties:
                        name:
                          type: string
                        subPath:
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                  storage:
                    properties:
                      resources:
                        default:
                          requests:
                            storage: 16Gi
                        properties:
                          requests:
                            default:
                              storage: 16Gi
                            properties:
                              storage:
                                default: 16Gi
                                type: string
                            type: object
                        type: object
                      storageClassName:
                        type: string
                    required:
                    - storageClassName
                    type: object
                  webDomain:
                    type: string
                required:
                - storage
                - webDomain
                type: object
            required:
            - plex
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: controller
  name: plex-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: controller
  name: plex-controller
rules:
- apiGroups:
  - illallangi.enterprises
  resources:
  - plexes
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: controller
  name: plex-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: plex-controller
subjects:
- kind: ServiceAccount
  name: plex-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: controller
  name: plex-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: plex
      app.kubernetes.io/name: controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: plex-controller
      labels:
        app.kubernetes.io/instance: plex
        app.kubernetes.io/name: controller
    spec:
      containers:
      - image: ghcr.io/illallangi/plex-controller:latest
        imagePullPolicy: Always
        name: plex-controller
      serviceAccount: plex-controller
      serviceAccountName: plex-controller
