---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: rsync
    app.kubernetes.io/name: controller
  name: rsyncs.illallangi.enterprises
spec:
  group: illallangi.enterprises
  names:
    kind: Rsync
    listKind: RsyncList
    plural: rsyncs
    singular: rsync
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.rsync.webDomain
      name: Domain
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              rsync:
                properties:
                  data:
                    properties:
                      name:
                        type: string
                      subPath:
                        type: string
                    required:
                    - name
                    type: object
                  webDomain:
                    pattern: ^[a-z][a-z0-9-]*\.great-tuna\.ts\.net$
                    type: string
                required:
                - data
                - webDomain
                type: object
              tailscale:
                properties:
                  apiToken:
                    oneOf:
                    - required:
                      - secretKeyRef
                    properties:
                      secretKeyRef:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                required:
                - apiToken
                type: object
            required:
            - rsync
            - tailscale
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: rsync
    app.kubernetes.io/name: controller
  name: rsync-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: rsync
    app.kubernetes.io/name: controller
  name: rsync-controller
rules:
- apiGroups:
  - illallangi.enterprises
  resources:
  - rsyncs
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: rsync
    app.kubernetes.io/name: controller
  name: rsync-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rsync-controller
subjects:
- kind: ServiceAccount
  name: rsync-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: rsync
    app.kubernetes.io/name: controller
  name: rsync-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: rsync
      app.kubernetes.io/name: controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: rsync-controller
      labels:
        app.kubernetes.io/instance: rsync
        app.kubernetes.io/name: controller
    spec:
      containers:
      - image: ghcr.io/illallangi/rsync-controller:latest
        imagePullPolicy: Always
        name: rsync-controller
      serviceAccount: rsync-controller
      serviceAccountName: rsync-controller
